### ISSUE TITLE
Timing warnings on Paper 1.19.4

### ISSUE THREAD

**Issue by stijnb1234** [aromaa/WorldGuardExtraFlags#238] opened 2023-04-09 13:57 UTC
I get a lot of timing warnings on Paper 1.19.4.

```
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnEntryFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'TeleportOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnExitFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'TeleportOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnEntryFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'CommandOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'CommandOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnEntryFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'ConsoleCommandOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnExitFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'ConsoleCommandOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.WalkSpeedFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'WalkSpeedFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.BlockedEffectsFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'BlockedEffectsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GodmodeFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GiveEffectsFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GiveEffectsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlyFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'FlyFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlySpeedFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'FlySpeedFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.PlaySoundsFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'PlaySoundsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[15:55:33 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GlideFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
```

**Comment by aromaa** [comment] 2023-04-09 14:18
Dupe of #236

**Closed by aromaa** 2023-04-09 14:18 UTC
