### ISSUE TITLE
Report The Author Warning

### ISSUE THREAD

**Issue by zikehalil3535** [aromaa/WorldGuardExtraFlags#239] opened 2023-04-11 14:41 UTC
WorldEdit: FastAsyncWorldEdit-391
WorldGuard  WorldGuard 7.0.7
WorldGuard Extra Flags: 4.2.1
Server: git-Purpur-1957 (MC: 1.19.4)

For old versions working correctly 
Example: git-Purpur-1948 (MC: 1.19.4)

![image](https://user-images.githubusercontent.com/88826436/231198481-d3395e20-cdeb-4fa7-9421-66b78f0bae02.png)

**Comment by aromaa** [comment] 2023-04-11 14:42
Dupe of #236

**Closed by aromaa** 2023-04-11 14:42 UTC
