### ISSUE TITLE
deprecated behavior

### ISSUE THREAD

**Issue by Distolfix** [aromaa/WorldGuardExtraFlags#250] opened 2023-06-17 17:03 UTC
[18:56:43 WARN]: Plugin 'WorldGuard' is creating timing 'Third-Party Session Handlers' - this is deprecated behavior, please report it to the authors: 
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'TeleportOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnExitFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'TeleportOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnEntryFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'CommandOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'CommandOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnEntryFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'ConsoleCommandOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnExitFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'ConsoleCommandOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.WalkSpeedFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'WalkSpeedFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.BlockedEffectsFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'BlockedEffectsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GodmodeFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GiveEffectsFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GiveEffectsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlyFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'FlyFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlySpeedFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'FlySpeedFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.PlaySoundsFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'PlaySoundsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:56:43 WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GlideFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3

**Comment by aromaa** [comment] 2023-06-17 17:07
Dupe of #236

**Closed by aromaa** 2023-06-17 17:07 UTC
