### ISSUE TITLE
WorldGuardExtraFlags using depreciated behavior

### ISSUE THREAD

**Issue by LichLord91** [aromaa/WorldGuardExtraFlags#243] opened 2023-05-05 18:49 UTC
On Minecraft 1.19.4 

```log
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'TeleportOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnExitFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'TeleportOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnEntryFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'CommandOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'CommandOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnEntryFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'ConsoleCommandOnEntryFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnExitFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'ConsoleCommandOnExitFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.WalkSpeedFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'WalkSpeedFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.BlockedEffectsFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'BlockedEffectsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GodmodeFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GiveEffectsFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'GiveEffectsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlyFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'FlyFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlySpeedFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'FlySpeedFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.PlaySoundsFlagHandler
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: isokissa3
[18:46:36] [Server thread/WARN]: Plugin 'WorldGuardExtraFlags' is creating timing 'PlaySoundsFlagHandler' - this is deprecated behavior, please report it to the authors: isokissa3
```

**Comment by aromaa** [comment] 2023-05-05 18:49
Dupe of #236

**Comment by LichLord91** [comment] 2023-05-05 18:50
*facepalm* sorry didn't search well enough. My bad!

**Closed by aromaa** 2023-05-05 18:49 UTC
